# Основы Python
Привет! Мы начинаем знакомство с языком Python. На первых порах для простоты мы будем писать все Python-программы в среде Jupyter. В ней уже все настроено и доступно из браузера - поэтому установка Python себе на компьютер не будет сейчас отвлекать. Текст, который ты читаешь, был написан в "ячейке" (англ. _cell_). "Ячейка" - это неразделимый кусок текста или кода, который Jupyter выполняет целиком.

Ячейка создается нажатием кнопки `+` выше в панельке. Попробуй создать новую ячейку, кликнуть на ее (появится курсор), написать в ней:
```python
1 + 5
```
и "выполнить" ее нажатием `Ctrl + Enter`. Внизу под ячейкой выведется число 6 - этот результат был подсчитан на Python.

Ячейки дают возможность сразу увидеть результат выполнения - этим они и удобны.

Знакомство с Python начнем с базовых конструкций языка.

### Ячейки
Весь Jupyter notebook состоит из _ячеек_ (англ. _cell_).

Ячейки в ноутбуке бывают трех типов:
1. `code` - содержат Python-код, который Jupyter выполнит.
2. `text` - содержат текст в разметке Markdown.
3. `raw` - содержат любые символы, которые Jupyter не будет пытаться как-либо выполнить (на практике используется редко).

Эта ячейка имеет тип `text`, и в ней написан текст. Если вы кликнете по ней два раза, то откроется исходный код текста - он станет немного другим.
Все дело в разметке: Markdown использует специальные символы для обозначения привычных вещей в тексте. Попробуйте кликнуть два раза по этому тексту и посмотрите на результат.

Чтобы выйти из исходного кода, можно нажать `Esc` (фон текста станет серее), но текст при этом останется некрасивым (или, корректнее, без применения разметки) - jupyter не прогонит его через себя и не превратит в красивый текст. Чтобы попросить Jupyter применить разметку, надо кликнуть на ячейку и нажать `Ctrl + Enter`.

Разметка Markdown проста и очень рекомендуется к изучению. Многие программные проекты используют ее для ведения документации (можно сказать, он так же часто используется для текстов в программирвании, как Word в бухгалтерии).
[Начать можно отсюда](https://www.markdownguide.org/getting-started/).

### Горячие клавиши
В Jupyter notebook много горячих клавиш (англ. _hotkey_). Это такие кнопки наподобие `Ctrl + C`, которые делают определенное действие.

Чтобы пользоваться горячими клавишами, надо выйти из режима редактирования текста - нажать `esc`. Курсор в тексте должен пропасть.
Горячих клавиш много, поэтому дадим список самых популярных:

- `esc` - выйти из режима редактирования ячейки
- `b` (как _below_) - создать ячейку внизу с типом `code`
- `a` (как _above_) - создать ячейку сверху с типом `code`
- `y` - сделать выбранной ячейке (это ячейка, вокруг которой зеленая рамка) тип `code`
- `m` (как _markdown_) - сделать выбранной ячейке тип `text`
- `dd` (как _delete_, только дважды) - удалить выбранную ячейку
- `x` - удалить ячейку и сохранить во временную память (не `Ctrl + C` - у jupyter на ячейки отдельный буфер обмена)
- `c` - скопировать ячейку и сохранить во временную память
- `v` - вставить ячейку из временной памяти _под_ текущей
- `V` (`shift + v`) - вставить ячейку из временной памяти _над_ текущей
- стрелка вниз - выбрать ячейку ниже
- стрелка вверх - выбрать ячейку выше
- `Ctrl + Enter` - исполнить текущую ячейку
- `Shift + Enter` - исполнить текущую ячейку и выбрать ячейку ниже

Попробуйте поиграть с этой ячейкой:
1. Создать под ней ячейку, превратить в тип `text` и написать туда, что вы ели сегодня на завтрак.
2. Скопиривать ячейку с завтраком, вставить _над_ ней, дать тип `code` и отредактировать в `print('hello')`.
3. Перейти на ячейку с завтраком и вырезать ее.
4. Вставить ячейку с завтраком.

Использования hotkeys неплохо экономит время на практике.

### Магические команды

Магические команды (англ. _magic commands_) - это дополнительная функциональность Jupyter, которая дает возможность менять поведение кода, добавлять подсчеты и чуть-чуть упрощает работу.
Давайте посмотрим на пример:

In [2]:
# Все magic commands начинаются с символа % и далее идет название
# Эта магия подсчитает время выполнения одной команды под ней
%time import numpy as np
for i in range(int(1e6)):
    i**2

CPU times: user 341 ms, sys: 147 ms, total: 488 ms
Wall time: 371 ms


Магия с двумя `%%` будет действовать на всю ячейку, но должна быть поддержка со стороны magic command.
`%time` по-умолчанию не работает с `%%`, надо ставить расширение на jupyter.

In [3]:
# Через ! можно сказать jupyter, что вся команду надо выполнить в терминале системы
# Jupyter поймет, что это не Python код
!pip install jupyter

Looking in indexes: https://ruabgne:****@artifactory.raiffeisen.ru/artifactory/api/pypi/remote-pypi/simple, https://ruabgne:****@artifactory.raiffeisen.ru/artifactory/api/pypi/cib-advanched-analytics-pypi/simple


In [4]:
import numpy as np
%time np.array([i**2 for i in range(int(1e6))])

CPU times: user 371 ms, sys: 26.2 ms, total: 397 ms
Wall time: 397 ms


array([           0,            1,            4, ..., 999994000009,
       999996000004, 999998000001])

Обратите внимание: когда ячейка выполняется, она выглядит вот так:
```
In [*]:
```
а когда ячейка выполнена, она выглядит как
```
In [14]:
```

Это отличительный знак: когда Jupyter ждет выполнения ячейки, он выставляет в `In [...]` звездочку.

In [5]:
# Посмотрим, какая магия нам доступна
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

In [6]:
%%time
# Cell magic - это магия, которая действует на всю ячейку
# cell magic обязательно должна быть первой строкой в ячейке
for i in range(int(1e6)):
    a = i**2

CPU times: user 291 ms, sys: 3.32 ms, total: 295 ms
Wall time: 293 ms


In [7]:
%load_ext autoreload
%autoreload 2

# autoreload делает так, чтобы все модули пере-импортировались перед тем, как запускать код
# По умолчанию Python так не делает: если модуль уже импортирован, он просто игнорирует импорт
# Если вы меняете исходный код модуля, изменения не подтянутся - autoreload как раз решает эту проблему

На практике чаще всего используют `%%time` для замера скорости ячейки, `%time` для замера скорости операции и `%autoreload` при разработке Python-пакета.

Оставим ссылки на документацию (не бойтесь ее читать!):

[Документация на magic](https://ipython.readthedocs.io/en/stable/interactive/magics.html) (IPython - это почти то же самое, что Jupyter)

[Документация на autoreload](https://ipython.org/ipython-doc/3/config/extensions/autoreload.html)

### Kernel

В Jupyter можно выполнять не только Python-коды, но и коды на других языках! Мы этим пользоваться не будем, но про возможность полезно знать.

За выполнение кода Python в Jupyter отвечает _ядро_ (англ. _kernel_). Нам здесь нужно знать две вещи: ядро можно менять на другое (скажем, то, где больше установленных пакетов) и ядро может зависать.

Ранее мы видели, `In [*]` означает, что ячейка считается.
На деле, эта запись означает другое: она говорит, что ядро занято.

Если ядро зависло или команда выполняется слишком долго, можно его _прервать_ (англ. _interrupt_). Для этого на панели наверху есть кнопка с изображением квадратика.

Ядро содержит в ОЗУ все когда-либо объявленные переменные ноутбука и может "жить" долго.
В больших проектах это может привести к тому, что ядро станет занимать очень много ОЗУ.

Если вам кажется, что ядро "раздулось", до больших размеров, то его можно перезапустить кнопкой, находящейся справа от кнопки _прерывания_.
Перезапуск ядра приведет к тому, что все переменные удалятся и все расчеты потеряются. Будьте готовы.

Кстати, на панельке сверху есть немало операций, которые мы изучили в секции "Горячие клавиши".

## Базовые операции
Посмотрим на основные операции, которые используются любым программистом на Python.

In [8]:
# Это комментарий. Питон игнорирует все, что написано после симовола # до конца строки
# А редактор это подсвечивает серым

# Пустые строки тоже игнорируются и никакого смысла не несут

# Знак = (равно) - это присваивание. Мы сейчас попросим записать в переменную "a" значение 5
a = 5

In [9]:
# Теперь по имени "a" можно вытащить его значение - сейчас это 5. Jupyter нам это покажет
a

5

In [10]:
# Арифметические операции можно делать как с числами
5 * 11

55

In [11]:
# Так и с участием переменных
11 * a

55

In [12]:
# Можно явно просить написать строку - это делается функцией print
# как в математке f(x) - функция f принимает аргумент x и делает над ним определенные действия
print(a)
# в нашем случае - печатает его

5


In [13]:
# print может принимать любое количество аргументов (делается через запятую)
# он распечатает их всех через пробел
print(4, 1, 'hello', a)

4 1 hello 5


In [14]:
# Можно делть нацело, отбрасывая дробную часть
5 // 2

2

In [15]:
# Остаток от деления берется через символ %
5 % 2

1

In [16]:
# Переменная может менять свое значение по ходу выполнения программы - отсюда и название
a = 10
print(a / 2)
a = 4
print(a / 2)

5.0
2.0


Из примера выше видно, что в одну ячейку можно положить несколько команд - Jupyter выполнит их последовательно. При этом Python ожидает, что каждая команда пишется с новой строки.

### Зачем нужны переменные?
У переменных два преимущества:
1. Делают логику независимой от чисел.
2. Делают преобразования данных читаемыми.

Приведем пример.
Представим, что мы хотим подсчитать доход через 5 лет по банковскому вкладу в разных банках. У нас есть 100 рублей и 2 банка с разными процентами:
1. Банк "Весна" дает 3% годовых.
2. Банк "Осень" дает 2% годовых, но более надежен.

Посчитаем, сколько будет денег через 5 лет:

In [17]:
3 ** 3  # 3 * 3 * 3

27

In [18]:
# Две звездочки - это оператор возведения в степень
# Обратите внимание на скобки - они указывают порядок операций
100 * ((100 + 3) / 100)**5

115.92740743

In [19]:
# Кстати, пробелы между операторами тоже игнорируются
100 * ((100 + 2) / 100) ** 5

110.40808032

Сходу глядя на код, не очень ясно, что означает первое число 100 и второе.
Нужно знать исходную задачу.

Давайте перепишем с использованием переменных.

In [20]:
initial_sum = 100
interest_rate = 3
years = 5
# Теперь из кода сразу ясно, как считается сумма в конце для любых входных данных
end_sum = initial_sum * ((100 + interest_rate) / 100)**years
end_sum

115.92740743

А еще можно легко пересчитать под другой процент, поменяв только вторую строчку - ту, что задает `interest_rate`.

### Другие типы переменных
В переменные можно класть не только числа! Есть строки, числа с дробной частью (в программировании их называют _числа с плавающей точкой_, англ. _float_) и многое другое.
#### Строки

In [21]:
# Строки заключаются в кавычки
# Двойные
name = "John"
# Или одинарные - разницы никакой
surname = 'Smith'
print(name)
print(surname)

John
Smith


In [22]:
print(2 ** 5)

32


В ячейке выше исполнилось 4 команды. Давай разберемся, что конкретно произошло:
1. Мы попросили записать в переменную `name` строку `John`
2. Мы попросили записать в переменную `surname` строку `Smith`
3. Мы попросили вызвать функцию `print` и передали аргументом ей переменную. Питон выполнил подстановку значения переменной и фактически вызвал функцию `print("John")`, которая, в свою очередь, распечатала строку `John`.
4. То же самое, что п.3, только передали переменную `surname`. После подстановки вызвалась `print("Smith")` и распечаталась строка `Smith`.

In [23]:
# На деле, у каждой переменной есть тип, просто Python его определяет сам
hello = 'hello'
# Распечатаем тип
print(type(hello))
print(hello)

# Python даже дает возможность менять тип на ходу! Не все языки программирования так щедры
hello = 2
print(type(hello))
print(hello)

<class 'str'>
hello
<class 'int'>
2


#### Boolean

In [24]:
# Булевый (англ. boolean) тип - это одно из слов "да" или "нет"
# Только Python предпочитает слова True и False :)
# Активно используется в проверке условий
my_bool = ('5' == 5)  # False, потому что сравнение учитывает типы
my_bool

False

In [25]:
my_bool_2 = ('el' in 'hello')  # True, потому что "hello" содержит подстроку "el"
my_bool_2

True

In [26]:
# Над булевыми типами есть операторы and, or, not
# Есть и другие, но на практике чаще использует эти три
# and требует, чтобы оба значения были True
a = 3
# == - это оператор равенства (не путайте с присваиванием!)
# проверяет, что значения слева и справа равны
(5 == 5) and (a == 3)

True

In [27]:
# or требует, чтобы хотя бы одно значение было True
(5 == 3) or (a == 3)

True

In [28]:
# not просто берет обратное значение
not (5 == 3)

True

In [29]:
# Обычно это все используется для сложной логики
my_name = 'Sasha'
(a == 3) or (my_name == 'Aleksei')

True

Порядок вычисления такой:

1. Скобки
2. `not`
3. `and`
4. `or`

In [30]:
# помимо == есть и другие операторы для сравнения
# больше либо равно
5 >= 2
# строго больше
print(5 > 2)  # булево значение можно передавать в функцию, как любое другое значение
# меньше либо равно (знак = в нем всегда идет вторым)
3 <= 1
# не равно
'hi' != 'bye'  # not (3 == 1)

True


True

## List, tuple, set
Часто в переменную имеет смысл положить не одно значение, а несколько.
Например, если мы захотим проводить анализ списка клиентов интернет-магазина за последний месяц, то имеет смысл держать их всех в одном месте, чтобы можно было удобно работать сразу со всеми элементами.

В Python для работы с набором данных есть несколько типов:
- list
- tuple
- set

Будем знакомиться по-отдельности с каждым.
### List
Набор элементов, в который можно класть объекты, доставать их и удалять.
Запоминает порядок, в котором элементы были добавлены.

In [31]:
# Объявляется через квадратные скобки и содержимое отделяется запятой
my_list = [1, 2, 3, 5]
my_list

[1, 2, 3, 5]

In [32]:
# Можно обратиться к элементу по порядку через квадратные скобки
# Заметьте, нумерация начинается с нуля
my_list[1]  # второй элемент в списке

2

In [33]:
len(my_list)  # запросим длину

4

In [34]:
# Элементы списка не обязаны быть одного типа
# можно даже класть в список другой список
my_list = ['a', 1, 3.14, [1, 2]]
print(my_list)

['a', 1, 3.14, [1, 2]]


In [35]:
# К списку можно "прибавить" другой список - один список добавится к концу другого
new_list = my_list + ['h', 'e', 'l', 'l', 'o']
new_list

['a', 1, 3.14, [1, 2], 'h', 'e', 'l', 'l', 'o']

In [36]:
# Можно добавлять через функцию append
new_list.append('g')
new_list
# Выполните несколько раз эту ячейку - каждый раз append будет добавлять в список

['a', 1, 3.14, [1, 2], 'h', 'e', 'l', 'l', 'o', 'g']

In [37]:
# Можно удалять элемент, зная его индекс (0 - начало массива, 1 - второй элемент и т.д.)
# Удалит первый элемент (позиция 0)
deleted_item = new_list.pop(0)
print(deleted_item)
# pop() без аргументов удалит последний элемент
print(new_list.pop())
# Если много раз выполнить, можно опустошить весь список :)

a
g


In [38]:
new_list

[1, 3.14, [1, 2], 'h', 'e', 'l', 'l', 'o']

In [39]:
# Можно удалять по значению, а не индексу
# Если элемента не найдется, то вылезет ошибка
print(new_list)
new_list.remove('h')
print(new_list)

[1, 3.14, [1, 2], 'h', 'e', 'l', 'l', 'o']
[1, 3.14, [1, 2], 'e', 'l', 'l', 'o']


#### Когда применять
Когда хотим класть много данных в одно логическое место. Например, список заказов одного клиента.

Если хотим добавлять элементы, следить за их взаимным порядком и удалять - самое то.

### Tuple (по-русски "кортеж")
Точно такой же, как `list` - только нет `append` и `remove` (т.е. в существующий `tuple` не получится положить еще элемент или же удалить его). Это из-за того, что объект tuple, будучи созданным, не может быть изменен (а добавление элемента в tuple - это его изменение).

In [40]:
my_tuple = (1, 2, 3)
my_tuple

(1, 2, 3)

In [41]:
my_tuple[1]

2

In [42]:
# Можно складывать, как и list
# при этом создастся новый (!) tuple, куда копируется сначала первый, потом второй
my_tuple + (5, 5)

(1, 2, 3, 5, 5)

In [43]:
(5, 5) + my_tuple

(5, 5, 1, 2, 3)

In [44]:
len(my_tuple + (1, 3, 'aaa',))

6

In [45]:
# В остальном - похож на list
my_tuple[1]

2

#### Когда применять
Когда требуются удобства list, но и в то же время неизменяемость. Подробнее об этом поговорим на уроке 2.

## Изменяемые и неизменяемые типы данных
В примере выше мы почуяли, что `.append()` изменяет само место в памяти, где лежит список - он добавляет к нему элемент.

Такую операцию над своими данными поддерживают не все типы. Некоторые типы данных не дают себя менять - как вы их создали в памяти, такими они и останутся до конца. Такие типы данных называются **неизменяемыми**. Чтобы сделать изменение, надо создать новый объект в памяти и положить туда все значения, которые останутся после предлагаемых изменений.

К примеру, строки в Python неизменяемые, но тем не менее их можно складывать:

In [46]:
sum_string = 'a' + 'b'
sum_string

'ab'

Под капотом это работает так: в памяти выделяется место под новую строку, после чего в это место сначала копируется целиком левая строка, потом правая, и ссылка на результат записывается в `sum_string`.
Поэтому складывать строки не рекомендуется - вы будете тратить лишние вычисления на копирования внутри памяти.

Обычно неизменяемые типы данных не имеют каких-либо функцию или операторов, изменяющих значения, чтобы не путать людей, но могут быть операторы `+` для их сложения (через копирование, как описано выше).

Например, кортеж (_tuple_) неизменяем - и у него нет `.append()`, `.delete()`, `.pop()`. Но складывать их можно: как и со строками, создатся копия, состоящия из объектов слева и справа.

In [47]:
(1, 3) + (2, 5, 8)

(1, 3, 2, 5, 8)

На первый вгляд такие знания кажутся тонкостью, но в реальной разработке незнание этих фактов может привести к просадке в производительности из-за необдуманных копирований.
Мы разберем задачу на это в блоке собеседований.

## Срезы
Срез - это кусок из списка или кортежа (вообще всего, что имеет упорядоченные индексы).

Проще показать:

In [48]:
a = [1, 5, 8, 3, 4]
a[2:4]  # забрать элементы с третьего по пятый НЕ включительно (третий, четвертый)

[8, 3]

In [49]:
# если опустить первый аргумент, то будет от начала списка
a[:4]  # по пятый НЕ включительно

[1, 5, 8, 3]

In [50]:
# если опустить второй аргумент, то будет до конца списка
a[2:]

[8, 3, 4]

In [51]:
# нумеровать можно отрицательными числами
# ниже описывается пример, как это будет считаться
# [1, 5, 8, 3, 4]
#  0  1  2  3  4
# -5 -4 -3 -2 -1

a[1:-1]  # правый конец не включается, поэтому отдаст список со второго по предпоследний элемент

[5, 8, 3]

In [52]:
# Может ничего не попасть
a[-1:-2]

[]

In [53]:
a[-2:-1]

[3]

In [54]:
# Есть еще третий аргумент - это шаг. Его можно пропустить
a[1:4:2]

[5, 3]

In [55]:
a[::2]  # выдаст первый, третий и т.д.

[1, 8, 4]

In [56]:
a[::-1]  # каждый "минус первый" - это каждый первый, только в обратном порядке, т.е. просто развернет лист

[4, 3, 8, 5, 1]

In [57]:
# развернет и через один
a[::-2]

[4, 8, 1]

In [58]:
a[3:1:-1]  # учтите, что в квадратных скобках индексы задаются от неразвернутого листа
# тут левый конец больше правого - при обратном порядке это нормально

[3, 8]

In [59]:
# но при прямом это не сработает (от четвертого элемента до второго при движении вправо нет ничего)
a[3:1]

[]

Срезы работают над кортежами и строками:

In [60]:
(1, 5, 9)[1:]

(5, 9)

In [61]:
'hello'[:1:-1]

'oll'

## Продвинутая работа со строками
В оставшемся куске рассмотрим приемы со строками, которые часто используются на практике.

In [62]:
# проверка символа
'l' in 'hello'

True

In [63]:
# проверка подстроки
print('ll' in 'hello')
print('wl' in 'hello')

True
False


In [64]:
# регистр
print('HeLlO'.lower())
print('hello'.upper())

hello
HELLO


In [65]:
# В нижнем ли регистре
print('hello'.islower())
print('Hello'.islower())

True
False


In [66]:
# В верхнем ли регистре
print('HELLO'.isupper())

True


In [67]:
# Поменять все найденные куски
# .replace(кого, на_что)
'hello llevo'.replace('ll', 'mm')

'hemmo mmevo'

In [68]:
'abra'.replace('zz', 'ww')  # если не нашел, то ничего не делает

'abra'

In [69]:
# Разбить строку по пробелам
'Сегодня чудесный день'.split()

['Сегодня', 'чудесный', 'день']

In [70]:
# Убрать мусорные пробелы вокруг строки (но не внутри!)
'   После опознания текста много    пробелов     '.strip()

'После опознания текста много    пробелов'

In [71]:
# Хорошо комбинировать split() и strip()
bad_string = '   После опознания текста много    пробелов     '
result = []
for word in bad_string.split():
    target = word.strip()
    result.append(target)
    
result

['После', 'опознания', 'текста', 'много', 'пробелов']

Запомните `split()` и `strip()` - с ними часто приходится иметь дело на практике.

### Set
Близок к "множествам" из математики. Особенен тем, что хранит уникальные элементы.

Не запоминает порядок элементов.

In [72]:
a = {2, 'a', 3.14}
a

{2, 3.14, 'a'}

In [73]:
b = set()
b

set()

In [74]:
# Добавим элемент
a.add(3)
a

{2, 3, 3.14, 'a'}

In [75]:
# Еще раз добавим - вот только он не добавится
# В set никогда не дублируются элементы - если элемент уже есть, он его не добавит
a.add(3)
a

{2, 3, 3.14, 'a'}

In [76]:
# Можно удалить. Если элемента нет, то вылезет ошибка, надо за этим следить
a.remove(3.14)
a

{2, 3, 'a'}

In [77]:
# a[0] - так нельзя

В `set` можно добавлять **только** неизменяемые объекты!
Это связано с его внутренним строением.
Так, создать множество вида `{2, "hello", []}` не получится, т.к. третий элемент имеет тип `list`, а он изменяемый.

Можно брать пересечения множеств, объединение, симметричную разность:
- `a.intersection(b)`
- `a.union(b)`
- `a.symmetric_difference(b)`

In [78]:
a = {'a', (1, 2), 3}
b = {3, (1, 2), 'unique'}
a.intersection(b)

{(1, 2), 3}

In [79]:
a.union(b)

{(1, 2), 3, 'a', 'unique'}

In [80]:
a.symmetric_difference(b)

{'a', 'unique'}

In [81]:
a - b

{'a'}

In [82]:
b - a

{'unique'}

#### Когда применять
1. Если нужно получить только уникальные элементы и порядок элементов не важен. Самый частый на практике кейс.
2. Если нужно узнать пересечение и прочие операции над множествами.

## Словарь
Хорошо, мы можем собрать список клиентов в одном месте, сохранить в переменную с удобным именем и иметь возможность дальше обращаться к переменной.

Но что, если мы захотим для каждого клиента хранить еще его номер телефона? Скажем, иметь что-то в духе адресной книги:


| Имя     | Номер             |
|---------|-------------------|
| Алексей | +7 123 123-12-34  |
| Никита  | +43 321 321-32-10 |

В Python для этого используются _словари_ (англ. _dict_, сокращенно от _dictionary_). Давайте посмотрим на пример:

In [83]:
# ключами может быть любой неизменяемый объект (строка, int, tuple) - как в set
name_to_number = {
    'Алексей': '+7 123 123-12-34',
    'Никита': '+43 321-32-10'
}
print(name_to_number)

{'Алексей': '+7 123 123-12-34', 'Никита': '+43 321-32-10'}


In [84]:
# По ключу можно вытащить значение
name_to_number['Алексей']

'+7 123 123-12-34'

In [85]:
# При этом, если ключа нет, то вылезет ошибка
# Можно сделать без ошибки: попросить возвращать некое значение по-умолчанию, если ключ не найден
print(name_to_number.get('Никита', 'no info'))
# Выведет +43 321-32-10, т.к. ключ "Никита" присутствует в словаре

print(name_to_number.get('Мария', 'no info'))
# Выведет "no info", т.к. ключа "Мария" нет в словаре

+43 321-32-10
no info


In [86]:
# В словарь легко добавлять элементы через оператор присваивания
name_to_number['Владимир'] = '+1 111 111-11-11'
print(name_to_number['Владимир'])
# через оператор in можно узнать, есть ли ключ в словаре
'Владимир' in name_to_number

+1 111 111-11-11


True

In [87]:
name_to_number

{'Алексей': '+7 123 123-12-34',
 'Никита': '+43 321-32-10',
 'Владимир': '+1 111 111-11-11'}

In [88]:
# И точно также можно редактировать через присваиваение
name_to_number['Владимир'] = 'hidden'
name_to_number['Владимир']

'hidden'

## Условия и циклы
Отлично, мы можем хранить много объектов в списках, хранить соответствия между объектами в словаре.

Но вместе с кучей объектов приходит вопрос: как их обрабатывать? Писать код на обработку каждого элемента - занятие неблагодарное.
К счастью, в Python есть _циклы_, которые позволяют применять набор операций к каждому элементу из списка.

### Цикл for
Пробегает по всем элементам и выполняет набор операций. Пример:

In [89]:
for a in [9, 16, 25]:
    print('считаем в цикле')
    print(a ** 0.5 + 1)
print('Пишем один раз')

считаем в цикле
4.0
считаем в цикле
5.0
считаем в цикле
6.0
Пишем один раз


Цикл пишется по простому синтаксису:
```python
for один_элемент in список_или_tuple_или_set:
    операция_1
    операция_2
```
В _один_элемент_ на каждом прогоне (или _итерации_) один за другим будут записываться объекты из списка.

Обратите внимание на двоеточие в конце строки (:) и отбивку табуляцией (или 4-мя пробелами) - это требования синтаксиса.
Через отбивку пробелами Python "понимает", какие команды надо повторять в цикле, а какие нет. При этом команды, которые цикл будет повторять раз за разом, называются _телом цикла_.

В примере выше первые два `print` идут в цикле, а последний - нет, поэтому он исполняется только один раз. Попробуте добавить в список `[9, 16, 25]` еще несколько значений и посмотрите, как поменяется вывод.

Давайте посмотрим, как это может применяться на практике:

In [90]:
# range(n) сгенерирует все числа от 0 до n-1 (последний не входит!)
# range очень часто встречается на практике, на нем остановимся детальнее
for i in range(5):
    print(i)

0
1
2
3
4


In [91]:
# range(start, stop) сгенерирует все числа от start до stop - 1
for i in range(1, 7):
    # f"что-то" называется f-string
    # через него можно подставить значение Python-выражения прямо в строку
    print(f'Квадрат числа {i} есть {i * i}')

Квадрат числа 1 есть 1
Квадрат числа 2 есть 4
Квадрат числа 3 есть 9
Квадрат числа 4 есть 16
Квадрат числа 5 есть 25
Квадрат числа 6 есть 36


In [92]:
print('Генерируем четные числа')
# range(start, stop, step) генерирует от start до (stop - 1) с шагом step
even_numbers = []
for i in range(0, 14, 2):
    even_numbers.append(i)
print(even_numbers)

Генерируем четные числа
[0, 2, 4, 6, 8, 10, 12]


### Цикл while
Если цикл `for` бегал по элементам из набора, то циклу `while` не нужны никакие списки.
Он просто прогоняет код в своем _теле цикла_ до тех пор, пока верно некое утверждение.

Давайте посмотрим, как это может работать:

In [93]:
# Представим, что нас попросили подсчитать, сколько раз число делится на 2
number = 34624

# Мы заранее не можем знать, сколько раз число поделится на 2 - тут и выручает while
while number % 2 == 0:  # кстати, number % 2 == 0 - имеет булевый тип
    print('делится на 2, делим')
    number //= 2 # то же самое, что number = number // 2
print(number)

делится на 2, делим
делится на 2, делим
делится на 2, делим
делится на 2, делим
делится на 2, делим
делится на 2, делим
541


Что делает `==`? Это оператор, проверящий на равенство: `number % 2 == 0` проверяет, равен ли остаток от деления на два нулю (проверка на четность). Если это так, то все конструкция обратится в `True` - это увидит `while` и войдет внутрь цикла.

Как только `number % 2 == 0` станет `False` (т.е. остаток перестанет быть нулем), цикл `while` "увидит" это и воспримет как сигнал завершения - больше внутрь цикла заходить не будет. После этого выполнится `print(number)`.

### Условный оператор: `if`

Представим ситуацию, когда нам дан на входе список балансов на счетах клиентов и нам надо вывести все счета с отрицательным балансом.
В голову приходит сравнивать баланс с нулем и если он меньше нуля, то записать в ответ. Но как объяснить Питону это "если"?

На помощь приходит оператор `if`:

In [94]:
# Простой пример для затравки: в зависимости от четности пишем разные сообщения
number = 4
if number % 2 == 0:
    print('число четное')
else:
    print('Число нечетное')

число четное


In [95]:
# А теперь поищем счета с отрицательным балансом
accounts_balance = [1482.0, 28182.12, -124.42, 85.3, -23.5, 82]  # входные данные

# сюда запишем ответ
negative_accounts = []
# проходимся по всем элементам во входных данных
for balance in accounts_balance:
    # если значение текущего элемента < 0, то идем во внутрь `if`
    if balance < 0:
        print(f'{balance} отрицателен, записываем в ответ')
        negative_accounts.append(balance)
    # выполнится в любом случае, т.к. не находится под властью `if` (отступы важны!)
    print(f'закончили обрабатывать баланс {balance}')
    
print(f'Отрицательные балансы: {negative_accounts}')

закончили обрабатывать баланс 1482.0
закончили обрабатывать баланс 28182.12
-124.42 отрицателен, записываем в ответ
закончили обрабатывать баланс -124.42
закончили обрабатывать баланс 85.3
-23.5 отрицателен, записываем в ответ
закончили обрабатывать баланс -23.5
закончили обрабатывать баланс 82
Отрицательные балансы: [-124.42, -23.5]


Сразу посмотрим на коснструкцию `if`. Ничего не напоминает? Синтаксис точно такой же, как у `while` - и это не спроста: в Python `for`, `while` и `if` являются _блочными_ конструкциями: они формируют блоки и каким-то образом их контролируют (`for` и `while` формируют блок повторяющихся операций, а `if` формирует блок, который выполнится при определенном условии).

`if` достаточно умен, чтобы обрабатывать сразу несколько случаев:

In [97]:
# input() - это запрос ввода от пользователя
# У вас появится внизу строка, куда можно ввести что угодно и это запишется в `name`
# Попробуйте ввести в строку "Москва" и "Лондон" без кавычек (запустите ячейку два раза)
name = input()
if name == 'Москва':
    print('Столица России')
# else if
elif name == 'Лондон':
    print('Столица Великобритании')
else:
    print('Неизвестно')

 Москва


Столица России


Работает следующим образом: если условие после `if` не выполнено, то идут проверяться условия после `elif` в том порядке, в каком они записаны в коде. Отбирается первое правильное - и в его блок исполняется. Если ничего не нашлось, то выполняется код из `else`.


### break, continue
Расскажем напоследок про два важных дополнения к `for` и `while`: это команды `break` и `continue`. Оба дают возможность выйти из цикла раньше задуманного:

In [98]:
words = ['see', 'this', 'long', 'sentence', 'here', 'no-show', 'no-show']
for i in range(len(words)):
    # Если треье слово - вылезаем досрочно
    print(words[i])
    if i > 2:
        # Выведет досрочно из цикла
        break

see
this
long
sentence


In [99]:
for i in range(5):
    for j in range(7):
        print(i, j)
        if j > 2:
            # Выкинет только из внутреннего цикла
            # Увидим, что i в выводе принимает значения 3, 4
            # это ожидаемо: break происходит после print(i, j) и одна итерация "просачивается"
            break
    print('увеличиваем i')

0 0
0 1
0 2
0 3
увеличиваем i
1 0
1 1
1 2
1 3
увеличиваем i
2 0
2 1
2 2
2 3
увеличиваем i
3 0
3 1
3 2
3 3
увеличиваем i
4 0
4 1
4 2
4 3
увеличиваем i


`continue` работает схожим образом, только не выходит целиком из цикла, а пропускает одну итерацию:

In [100]:
for feature in ['make sandwitch', 'make coffee', 'watch TV', 'wash plate']:
    if feature == 'make coffee':
        # Пропустим одну итерацию в цикле
        print('Coffee machine is broken, skipping :(')
        continue
    # else уже не нужен - если условие не истинно
    # то все равно выйдем на print ниже
    # а если истинно - continue гарантирует, что дальше цикл выполняться не будет
    print(f'starting action: {feature}')

starting action: make sandwitch
Coffee machine is broken, skipping :(
starting action: watch TV
starting action: wash plate


Для чего это может быть нужно? Иногда в логике цикла бывают отклонения: скажем, определенную комбинацию параметров нельзя обрабатывать циклом - тогда используем `continue`.

`break` чаще всего используется в циклах `while` как уточнение, когда останвливать цикл.
Пример: в машинном обучении есть алгоритм градиентного спуска, который "учит" модель на данных. Процесс "обучения" идет по шагам, и часто процесс надо прервать, если новый шаг не привел к улучшению модели - в таких случаях можно применить `break` для выхода.

## Функции
### Зачем нужны функции
Функции в Python выполняют схожую функцию, что и указания в устной речи.
Когда мы говорим "Возьми на столе список покупок и сходи за ними в магазин", человек сразу понимает набор действий, который надо совершить:
1. Взять листик со стола и положить себе (листик был бы _аргументом_ функции).
2. Сходить в магазин.
3. Для каждого товара из листика - найти в магазине и положить в корзину.
4. Подойти к кассе и рассчитаться.
5. Вернуться домой.
6. Отдать покупки (покупки были бы _возвращаемым значением_ функции).

При этом человеку не надо каждый раз объяснять, как ходить в магазин - достаточно один раз (обычно это происходит в возрасте 6-7 лет) объяснить, как покупать в магазине.

Сохранение действий в одно имя может здорово помочь в разработке:
1. Оно уменьшает количество строк кода. Если один раз человеку объяснить, как ходить в магазин, то потом не нужно снова тратить на это слова.
2. Оно разбивает код на логические блоки, каждый из которых четко говорит, что он делает. Если мы видим в тексте, что идет описание "как ходить в магазин", то мы можем пропустить это описание, если уже знаем, как ходят в магазин, либо же читать только этот кусок, если хотим разобраться. Главное - нам не придется читать весь текст вместе с другими командами и пытаться понять целиком и сразу, что там делается.

Давайте рассмотрим игрушечный пример:

In [101]:
def say_hello(name):
    print(f'Hello, {name}')

user_name = input('Please enter your name:')  # в input() можно передать строку - ее Питон выведет, когда будет просить ввести строку
say_hello(user_name)

Please enter your name: Нерсес


Hello, Нерсес


В функции мы попросили выполнить ровно одно действие: напечатать `Hello, {name}` с подстановкой значения переменной `name` (для подстановки использовали f-strings, о которых говорили в первой лекции).

**Важный момент**: мы нигде до этого не объявляли переменную `name`, но тем не менее уже используем ее в коде функции. Почему так можно, разберемся немного позже, пока только подметим.

### Как работать с функциями
Жизнь функции состоит из двух этапов: объявления и вызова.
Объявление функции - это описание имени функции, всех входных значений, всех совершаемых функцией действий и возвращаемого результата (_в примере отсутствует_, будет ниже).
Функция объявляется через слово `def`. Его синтаксис такой:
```python
def function_name(argument_1, argument_2, ...):
    action_1
    action_2
    ...
    return value_to_return
```

In [102]:
# Учим Python определять, четное число или нет
def is_even(number):  # объявляем по синтаксису выше. Обратите внимание на двоеточие в конце - оно обязательно
    # Все команды внутри функции пишутся через табуляцию - как и в циклах.
    # Это не удивительно, поскольку команды, которые выполняет функция,
    # формируют блок - точно такой же блок, что мы видели в циклах и условиях if
    if number % 2 == 0:
        return True
    else:
        return False


print(is_even(2))  # вызываем функцию, передавая на вход один аргумент 2
print(is_even(9))

True
False


Почему же функция "видит" переменную под другим именем?

Дело в том, что при вызове функций в нее передаются _аргументы_, которые внутри функции будут видны как переменные.
В примере выше функция `is_even` принимает один _аргумент_ `number` (такое имя мы указали на этапе _объявления_ функции) и теперь внутри `is_even` (и только там!) можно писать код, считая переменную `number` заданной.
Когда мы далее _вызываем функцию_, ей будет передано число `2` как первый аргумент - и далее функция будет "видеть" число `2` как переменную с именем `number`.

Кстати, мы ранее вызывали функцию `print()` по схожим правилам :)

### Чем функции отличаются от циклов
На первый взгляд кажется, что для набора повторяющихся операций уже есть циклы. 
Но функции несколько про другое: вместо того, что повторять набор операций сразу, они "сохраняют" этот набор под некоторым именем, чтобы дальше можно было по этому имени выполнить набор целиком. В примере с магазином мы все 6 операций сохранили бы под именем "сходи в магазин" и затем периодически бы вызывали этот набор через фразу "сходи в магазин".

In [103]:
# Попробуем подсчитать прибыль по вкладу, как это делали в первом занятии, но через функции

def balance_after_a_year(init_sum, interest_rate):
    """
    Через тройные кавычки (одинарные или двойные - без разницы, но рекомендуют двойные)
    можно писать комментарии к функции, по которым потом можно генерировать документацию через сторонние инструменты.
    Про документацию мы еще поговорим, а пока что запомним, что сюда лучше писать, что делает функция.
    
    Подсчет баланса через 1 год
    """
    return init_sum * (100 + interest_rate) / 100

def full_profit(init_sum, interest_rate, years):
    """Подсчет баланса через years лет"""
    final_sum = init_sum
    for i in range(years):
        final_sum = balance_after_a_year(final_sum, interest_rate)
    return final_sum - init_sum

In [104]:
full_profit(1000, 5, 2)

102.5

### Аргументы по-умолчанию
В примере с балансом выше мы объявили в функции `full_profit`, что она принимает три аргумента.
Но это одновременно стало и обузой: теперь этой функции надо передавать обязательно три аргумента.

Смотрите сами, сейчас мы получим ошибку:

In [105]:
full_profit(1000, 5)

TypeError: full_profit() missing 1 required positional argument: 'years'

Не пугайтесь красного цвета, все не так плохо! Вы только что увидели свою первую ошибку (или _исключение_, как их могут называть в других языках программирования).

В ошибке пишут обычно ее имя (это `TypeError` в последней строке, выделено красным), затем через двоеточие пишут текст ошибки, который должен помочь понять, что пошло не так. У нас это `full_profit() missing 1 required positional argument: 'years'` - функции `full_profit` не хватает одного аргумента `years` (мы передали 2 аргумента, а ожидается 3).

К ошибкам надо привыкать, на первых порах они будут у вас встречаться сплошь и рядом :)
Не бойтесь читать ошибки, в нх очень часто прячется подсказка, как ее исправить! Обычно самая информативная часть находится в конце текста ошибки, начинать лучше оттуда.

Но как же нам быть, если мы хотим вызывать `full_profit` с двумя аргументами? Можно задать _значение по-умолчанию_. Скажем, если `years` не указано, то пусть будет 1 год.

In [106]:
# Посмотрите на years=1 - это единственное изменение
def full_profit(init_sum, interest_rate, years=1):
    """Подсчет баланса через years лет"""
    final_sum = init_sum
    for i in range(years):
        final_sum = balance_after_a_year(final_sum, interest_rate)
    return final_sum - init_sum

In [107]:
full_profit(1000, 5)

50.0

Значения по-умолчанию можно выставить хоть всем аргументам. Но учтите, что если вы начали с какой-то переменной раздавать значения по-умолчанию, то теперь придется это делать для всех (такая особенность Python).

In [108]:
def official_greeting(first_name='Василий', middle_name='Иванович'):
    print(f'Здравствуйте, {first_name} {middle_name}')
    

# Тройные кавычки обозначают многострочный комментарий - их можно не только для документации функции использовать
# Таким способом можно изолировать "опасный" код
# Попробуйте убрать тройные кавычки и посмотрите, как возникает ошибка.
# Не забудьте вернуть кавычки :)
"""
# Код ниже не работает, т.к. middle_name должно иметь значение по-умолчанию, поскольку fist_name перед ним уже имеет
# Напишет ошибку "non-default argument follows default argument"
def official_greeting(first_name="Василий", middle_name):
    print("Этот код не работает")
"""

official_greeting()
official_greeting("Иван", "Николаевич")

Здравствуйте, Василий Иванович
Здравствуйте, Иван Николаевич


# Сторонние библиотеки
Мы уже много узнали про встроенные структуры данных (`list`, `dict`, `set`, `tuple`) и про функции над ними.
Но Python не стал бы таким популярным, если бы не написанные к нему библиотеки :)

Сейчас мы рассмотрим, как импортировать библиотеки и потыкаем несколько встроенных в Python библиотек.


## Что такое библиотека
Библиотека - это набор готовых функций и переменных, которые можно использовать в своем коде. В Python уже есть несколько встроенных библиотек, которые мы уже можем использовать.

Библиотеки могут также называть _пакетами_. В повествовании мы будем иногда их так называть, не пугайтесь - это одно и то же.

### Простой импорт на примере `datetime`
Практический пример: в анализе данных часто приходится иметь дело с датами. Давайте посмотрим, как работать с ними через библиотеку `datetime`:

In [109]:
# просим подключить библиотеку под названием datetime
import datetime

# синтаксис простой

# import название_библиотеки

In [110]:
# теперь можно обращаться к библиотеке через ее название и точку
# вызовем date() из библиотеки datetime
christmas_day = datetime.date(year=2022, month=1, day=7)  # явно передаем имя аргумента, не привязываясь к порядку
print(christmas_day)

2022-01-07


In [111]:
# в datetime куча всего для работы со временем. Например, можно писать точную дату и время
# для этого вызовем datetime() из библиотеки datetime (да, такая тавтология)
# она вернет объект с датой и временем
some_time = datetime.datetime(2022, 3, 4, 13, 55, 34)

print(f'Месяц {some_time.month}')
print(f'День {some_time.day}')
print(f'Час {some_time.hour}')
print(f'Минута {some_time.minute}')
print(f'Секунда {some_time.second}')

Месяц 3
День 4
Час 13
Минута 55
Секунда 34


In [112]:
# Сложение и вычитание дат/веремени делается через timedelta
delta_1 = datetime.timedelta(days=60)

# Прибавляем 60 дней к дате 2021-03-12
print(datetime.date(2021, 3, 12) + delta_1)

2021-05-11


В пакете `datetime` (иногда пакеты называют _модулями_, хотя это не совсем корректно) есть много другого.
Подробнее можно прочитать в [блоге pythonworld.ru](https://pythonworld.ru/moduli/modul-datetime.html).

### Импорт через `from` на примере  `collections`
`collections` - еще одна полезная встроенная библиотека.
Содержит дополнительные структуры данных, упрощающие жизнь.

На практике часто используются `defaultdict` и `Counter`.
#### `defaultdict`

In [113]:
# можно подключать не всю библиотеку, а отдельные объекты из нее
# подключим defaultdict и Counter из библиотеки collections
from collections import defaultdict, Counter

# общий синтаксис:

# from название_библиотеки import объект_1, объект_2, объект_3

"""
defaultdict - это обычный словарь, но при обращению к несуществующему элементу
он не выбрасывает ошибку, а создает его
"""
d = defaultdict(int)  # говорим, чтобы создавалось число 0 при остутствии элемента
# Почему defaultdict(int), а не defaultdict(0) - поговорим позже
print(d)
print(d["this key does not exist"])
print(d)

defaultdict(<class 'int'>, {})
0
defaultdict(<class 'int'>, {'this key does not exist': 0})


Видим, что при обращении к элементу `"this key does not exist"` он создался в словаре со значением `int()` - это нуль (убедитесь сами).
Обычный `dict` в этом случае бы выбросил ошибку.

####  `Counter`
`Counter` принимает на вход список, считает в нем элементы и возвращает словарь с результатом

In [114]:
array = [1, 3, 'a', 'm', 1, None, 3, 3, ()]

c = Counter(array)
c

Counter({1: 2, 3: 3, 'a': 1, 'm': 1, None: 1, (): 1})

Число `1` встретилось два раза, число `3` встретилось 3 раза, остальные элементы - по одному разу.

Обратите внимание: ключами в словаре могут быть только неизменяемые объекты.
Поэтому на вход в `Counter()` могут поступать только списки с неизменяемыми объектами.

In [115]:
# Counter - это такой же словарь, как и dict
c[1] += 1
print(c)

c['a'] = None
print(c)

Counter({1: 3, 3: 3, 'a': 1, 'm': 1, None: 1, (): 1})
Counter({1: 3, 3: 3, 'a': None, 'm': 1, None: 1, (): 1})


### Импорт через `as` на примере 
Конструкция `as` позволяет обращаться к пакету по другому имени в коде.
Это полезно, когда название пакета длинное и не хочется его полностью писать каждый раз.

Мы чуть позже сталкнемся с полезными примерами, пока что рассмотрим искусственный:

In [116]:
import json as j

# Преобразует словарь в JSON-формат
j.dumps({'a': True})

'{"a": true}'

Этот код равносилен коду:

In [117]:
import json
json.dumps({'a': True})

'{"a": true}'

## Numpy

Библиотека для работы с матрицами. Название происходит от **Num**eric **Py**thon.
"Под капотом" написана на C++ (это такой язык программирования, очень быстрый в умелых руках), а то, что видим в Python - это лишь "рычаги управления".

Используется как фундамент для построения популярных библиотек в ML: `pandas`, `scikit-learn` и т.п. Вы познакомитесь с `numpy` поближе в модуле "Машинное обучение", а пока мы обзорно посмотрим на его возможности.

In [118]:
import numpy as np

# Создаем матрцы
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [119]:
# количество осей/измерений
a.ndim 

2

In [120]:
# длина массива по каждой из осей
a.shape

(4, 3)

In [121]:
# тип элемента массива
a.dtype.name

'int64'

In [122]:
# размер элемента массива
a.itemsize

8

In [123]:
# Матрицу можно транспонировать ("повернуть на бок")
a.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [124]:
# Создание массивов специального вида при помощи функций
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [125]:
# Создание массивов специального вида при помощи функций
np.zeros(3,int)

array([0, 0, 0])

In [126]:
# Создание массивов специального вида при помощи функций
np.ones(7,int)

array([1, 1, 1, 1, 1, 1, 1])

In [127]:
# Создание последовательностей при помощи функций arange (в качестве парметров принимает левую 
# и правую границы последовательности и шаг) и linspace (принимает левую и правую границы и количество элементов):
start = 2
finish = 20
step = 3
np.arange(start, finish, step) 
# аналогично стандартной функции range правая граница не включается

array([ 2,  5,  8, 11, 14, 17])

In [128]:
np.arange(2.5, 8.7, 0.9) 
# но может работать и с вещественными числами

array([2.5, 3.4, 4.3, 5.2, 6.1, 7. , 7.9])

In [129]:
start = 2
finish = 18
count = 14
np.linspace(start, finish, count) 
# правая граница включается 

array([ 2.        ,  3.23076923,  4.46153846,  5.69230769,  6.92307692,
        8.15384615,  9.38461538, 10.61538462, 11.84615385, 13.07692308,
       14.30769231, 15.53846154, 16.76923077, 18.        ])

In [130]:
# Можно считать скалярные произведения
np.dot(a, np.array([1, 2, 3]))

array([14, 32, 50, 68])

In [131]:
# Обычные умножения делаются поэлементно. Немного непривычно для математиков
b = np.array([[-1, -2, -3], [-4, -5, -6], [-7, -8, -9], [-10, -11, -12]])
a * b

array([[  -1,   -4,   -9],
       [ -16,  -25,  -36],
       [ -49,  -64,  -81],
       [-100, -121, -144]])

In [132]:
b * a

array([[  -1,   -4,   -9],
       [ -16,  -25,  -36],
       [ -49,  -64,  -81],
       [-100, -121, -144]])

In [133]:
a + b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [134]:
a + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [135]:
3 * a

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27],
       [30, 33, 36]])

In [136]:
a ** 2

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [137]:
a * 1.0 / b

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

Для выполнения скалярного умножения необходимо использовать функцию dot:

In [139]:
a.dot(b.T)

array([[ -14,  -32,  -50,  -68],
       [ -32,  -77, -122, -167],
       [ -50, -122, -194, -266],
       [ -68, -167, -266, -365]])

In [140]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [141]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [142]:
a.min()
# max mean

1

In [143]:
a.sum()

78

## Индексация

Для доступа к элементам может использоваться [много различных способов](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html), рассмотрим основные.

In [144]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Индексация

In [145]:
a [5]

6

In [146]:
a[-2]

8

### Индексация списком индексов

In [147]:
a[[1,3,7]]

array([2, 4, 8])

### Логическая индексация

In [148]:
a>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [149]:
a % 2 != 0

array([ True, False,  True, False,  True, False,  True, False,  True])

In [150]:
a[(a % 2 != 0) & (a > 5)]

array([7, 9])

In [151]:
a[np.logical_and(a != 7, a % 5 != 3)] 

array([1, 2, 4, 5, 6, 9])

### Срезы / slice 

In [152]:
a[2:5]

array([3, 4, 5])

In [153]:
a[3:8:2]

array([4, 6, 8])

In [154]:
a[8:12]

array([9])

In [155]:
# перевернуть вектор
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

## Вектор случайных значений

In [156]:
minn = 5
maxx = 100
count = 15
np.random.randint(minn, maxx, count)

array([13, 35, 42, 36,  7, 72, 56, 79, 87, 34, 36, 46,  7, 88, 68])

## Зачем?

Зачем необходимо использовать NumPy, если существуют стандартные списки/кортежи и циклы?

Причина заключается в скорости работы. Попробуем посчитать сумму поэлементых произведений 2 больших векторов:

In [157]:
import time

A = np.random.normal(size = (1000000,))
B = np.random.normal(size = (1000000,))

a_list = list (A)
b_list = list (B)

In [162]:
start = time.time()
answer = 0
# ans = sum((a_list[i] * b_list[i] for i in range(1000000)))
for i in range (len(a_list)):
    answer += a_list[i] * b_list[i]
print(time.time() - start)

0.26514720916748047


In [164]:
start = time.time()
#ans = np.sum(A * B)
ans = A.dot(B)
print(time.time() - start)

0.0024547576904296875


### Создаем тензоры в pytorch и снова изучаем базовые операции

In [169]:
import torch

In [170]:
x = torch.empty(5, 3) # пустой тензор
print(x)

tensor([[ 1.3563e-19, -1.1627e+21, -3.6598e-25],
        [-9.0811e-34, -1.2598e+21, -3.6598e-25],
        [-9.0811e-34, -1.2598e+21, -3.6598e-25],
        [-9.0811e-34,  2.3139e-19,  1.3563e-19],
        [ 1.3563e-19,  1.3563e-19,  1.3563e-19]])


In [171]:
x = torch.rand(5, 3) # тензор со случайными числами
print(x)

tensor([[0.1824, 0.4151, 0.9427],
        [0.7296, 0.8985, 0.4015],
        [0.6564, 0.2385, 0.1815],
        [0.1419, 0.0331, 0.0137],
        [0.8828, 0.9313, 0.2358]])


In [172]:
x = torch.zeros(5, 3, dtype=torch.long) # тензор с нулями и указанием типов чисел
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [173]:
x = torch.tensor([5.5, 3]) # конструируем тензор из питоновского листа
print(x)

tensor([5.5000, 3.0000])


In [174]:
x = x.new_ones(5, 3, dtype=torch.double) # используем уже созданный тензор для создания тензора из единичек
print(x, x.size()) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.Size([5, 3])


In [175]:
x = torch.randn_like(x, dtype=torch.float) # создаем матрицу с размерами как у x
print(x, x.size())

tensor([[ 1.6514, -1.0750,  2.8929],
        [-1.3795, -1.1223,  1.2587],
        [ 1.0644, -0.1943,  0.0599],
        [ 0.4739, -0.7790, -0.9297],
        [ 0.9451,  0.4236, -1.0068]]) torch.Size([5, 3])


In [176]:
y = torch.rand(5, 3)
print(x + y) # операция сложение

tensor([[ 2.5281, -0.3194,  3.8872],
        [-1.0506, -0.2362,  1.6395],
        [ 1.3601,  0.7919,  0.2536],
        [ 1.3951, -0.6547, -0.4917],
        [ 1.1123,  0.5334, -0.5391]])


In [177]:
z = torch.add(x, y) # очередная операция сложения
print(z)

tensor([[ 2.5281, -0.3194,  3.8872],
        [-1.0506, -0.2362,  1.6395],
        [ 1.3601,  0.7919,  0.2536],
        [ 1.3951, -0.6547, -0.4917],
        [ 1.1123,  0.5334, -0.5391]])


In [178]:
torch.add(x, y, out=z) # и наконец последний вид
print(z)

tensor([[ 2.5281, -0.3194,  3.8872],
        [-1.0506, -0.2362,  1.6395],
        [ 1.3601,  0.7919,  0.2536],
        [ 1.3951, -0.6547, -0.4917],
        [ 1.1123,  0.5334, -0.5391]])


In [179]:
print(x * y) # поэлементное умножение

tensor([[ 1.4478, -0.8122,  2.8763],
        [-0.4537, -0.9945,  0.4793],
        [ 0.3147, -0.1916,  0.0116],
        [ 0.4366, -0.0968, -0.4071],
        [ 0.1581,  0.0465, -0.4709]])


In [180]:
print(x @ y.t()) # матричное умножение

tensor([[ 3.5119,  0.6922, -0.0115,  2.6545,  1.5113],
        [-0.8058, -0.9688, -1.2709, -0.8590,  0.2348],
        [ 0.8460,  0.2007,  0.1348,  0.9827,  0.1848],
        [-1.0974, -0.8884, -0.8082, -0.0673, -0.4410],
        [ 0.1476,  0.3028,  0.5022,  0.4824, -0.2663]])


In [181]:
print(x.mm(y.t())) # и опять матричное умножение

tensor([[ 3.5119,  0.6922, -0.0115,  2.6545,  1.5113],
        [-0.8058, -0.9688, -1.2709, -0.8590,  0.2348],
        [ 0.8460,  0.2007,  0.1348,  0.9827,  0.1848],
        [-1.0974, -0.8884, -0.8082, -0.0673, -0.4410],
        [ 0.1476,  0.3028,  0.5022,  0.4824, -0.2663]])


In [182]:
print(x.unsqueeze(0).shape) # добавили измерение в начало, аналог броадкастинга 

torch.Size([1, 5, 3])


In [183]:
print(x.unsqueeze(0).squeeze(0).shape) # убрали измерение в начале, аналог броадкастинга 

torch.Size([5, 3])
